package main

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"
)

const (
	clrReset  = "\033[0m"
	clrBold   = "\033[1m"
	clrFaint  = "\033[2m"
	clrAccent = "\033[33m" // yellow, matches the wasp theme
)

func runSetup() {
	r := bufio.NewReader(os.Stdin)

	fmt.Println()
	fmt.Println(clrBold + "  wasphole setup" + clrReset)
	fmt.Println("  " + strings.Repeat("─", 32))
	fmt.Println()

	// ── Instance ─────────────────────────────────────────────────
	mode := pickOne(r, "Simulated OS?", []string{"linux", "windows"})
	industry := askFree(r, "Industry?", "", "fintech, healthcare, saas … leave blank to skip")

	// ── AI ───────────────────────────────────────────────────────
	provider := pickOne(r, "AI provider?", []string{"anthropic", "openai"})

	baseURL := askFree(r, "Base URL?", "", "leave blank for default endpoint")

	envVar := "ANTHROPIC_API_KEY"
	defaultModel := "claude-sonnet-4-6"
	if provider == "openai" {
		envVar = "OPENAI_API_KEY"
		defaultModel = "gpt-4o"
	}

	apiKey := askFree(r, "API key?", "", "or set "+envVar+" env var — leave blank to skip")
	model := askFree(r, "Model?", defaultModel, "")

	// ── Transport ────────────────────────────────────────────────
	transport := pickOne(r, "Transport?", []string{"http", "stdio"})

	port := 8080
	if transport == "http" {
		raw := askFree(r, "Port?", "8080", "")
		if p, err := strconv.Atoi(raw); err == nil && p > 0 {
			port = p
		}
	}

	// ── Alerts ───────────────────────────────────────────────────
	webhook := askFree(r, "Alert webhook URL?", "", "optional — leave blank to skip")

	// ── Write ────────────────────────────────────────────────────
	outPath := "config.yaml"
	if _, err := os.Stat(outPath); err == nil {
		overwrite := askFree(r, "config.yaml already exists. Overwrite?", "no", "yes / no")
		if !strings.HasPrefix(strings.ToLower(overwrite), "y") {
			fmt.Println()
			fmt.Println(clrFaint + "  Aborted — config.yaml unchanged." + clrReset)
			fmt.Println()
			return
		}
	}

	if err := os.WriteFile(outPath, []byte(buildConfig(mode, industry, provider, baseURL, apiKey, model, transport, port, webhook)), 0o640); err != nil {
		fmt.Fprintf(os.Stderr, "  error writing config.yaml: %v\n", err)
		os.Exit(1)
	}

	fmt.Println()
	fmt.Println(clrAccent + "  ✓ config.yaml written" + clrReset)
	fmt.Println()
	fmt.Println(clrFaint + "  Next: wasphole server" + clrReset)
	fmt.Println()
}

// ── Prompt helpers ────────────────────────────────────────────────────────────

func pickOne(r *bufio.Reader, label string, options []string) string {
	for {
		fmt.Println("  " + clrBold + label + clrReset)
		for i, o := range options {
			fmt.Printf("  [%d] %s\n", i+1, o)
		}
		fmt.Print(clrAccent + "  → " + clrReset)
		raw := readLine(r)

		// Accept number or full word
		if n, err := strconv.Atoi(raw); err == nil && n >= 1 && n <= len(options) {
			fmt.Println()
			return options[n-1]
		}
		for _, o := range options {
			if strings.EqualFold(raw, o) {
				fmt.Println()
				return o
			}
		}
		fmt.Println(clrFaint + "  Please enter a number or one of: " + strings.Join(options, ", ") + clrReset)
	}
}

func askFree(r *bufio.Reader, label, def, hint string) string {
	display := "  " + clrBold + label + clrReset
	if def != "" {
		display += clrFaint + " [" + def + "]" + clrReset
	}
	if hint != "" {
		display += clrFaint + " (" + hint + ")" + clrReset
	}
	fmt.Println(display)
	fmt.Print(clrAccent + "  → " + clrReset)
	raw := readLine(r)
	fmt.Println()
	if raw == "" {
		return def
	}
	return raw
}

func readLine(r *bufio.Reader) string {
	line, _ := r.ReadString('\n')
	return strings.TrimSpace(line)
}

// ── Config builder ────────────────────────────────────────────────────────────

func buildConfig(mode, industry, provider, baseURL, apiKey, model, transport string, port int, webhook string) string {
	var b strings.Builder

	b.WriteString("# generated by wasphole setup\n\n")

	b.WriteString("instance:\n")
	b.WriteString("  mode: " + mode + "\n")
	if industry != "" {
		b.WriteString("  industry: " + industry + "\n")
	}
	b.WriteString("\n")

	b.WriteString("ai:\n")
	b.WriteString("  api_type: " + provider + "\n")
	b.WriteString("  base_url: \"" + baseURL + "\"\n")
	b.WriteString("  api_key: \"" + apiKey + "\"\n")
	b.WriteString("  model: " + model + "\n")
	b.WriteString("\n")

	b.WriteString("transport:\n")
	b.WriteString("  type: " + transport + "\n")
	if transport == "http" {
		b.WriteString("  port: " + strconv.Itoa(port) + "\n")
	}
	b.WriteString("\n")

	b.WriteString("alerts:\n")
	b.WriteString("  sinks:\n")
	b.WriteString("    - type: stdout\n")
	b.WriteString("      enabled: true\n")
	if webhook != "" {
		b.WriteString("    - type: webhook\n")
		b.WriteString("      url: " + webhook + "\n")
		b.WriteString("      enabled: true\n")
	}
	b.WriteString("\n")

	b.WriteString("session:\n")
	b.WriteString("  log_dir: ./sessions\n")

	return b.String()
}
